### ISSUE TITLE
Feedback on Canvas - Managing children

### ISSUE THREAD

**Issue by khionu** [linebender/druid-widget-nursery#26]
I've been blindly trying to make use of the Canvas widget, and I've been having issues trying to figure out why it seems that draw calls were not completing. The problem seems to be rooted [here](https://github.com/linebender/druid-widget-nursery/blob/master/src/canvas.rs#L120).

This highlights a gap in this module with respect to controlling the children within the Canvas. While there is some advantage to Canvas right now, this is a serious deficit to its usability. I think Canvas needs an API to allow the Canvas to move around and resize its children.

**Comment by khionu** [comment]
This actually calls into question the design goal of Canvas. To me, the concept should be more a place where you can paint specific widgets in specific positions with specific sizes, but the implementation depends on the widget to define some of this, which contradicts the perceived purpose?

I would appreciate input from someone who is familiar with the original intent of the concept and/or code.

**Comment by khionu** [comment]
We've been communicating on Zulip

**Comment by derekdreery** [comment]
I've not been involved in this.

**Comment by khionu** [comment]
Closing. Further exploration revealed that my use case probably needs to be its own widget.
