### ISSUE TITLE
New button

### ISSUE THREAD

**Issue by arthmis** [linebender/druid-widget-nursery#3]
Would it be possible to add a new button widget that adds more customizability, as far as display goes. In other words, being able to specify hover color, active color, and so on. I don't know if things like that are possible with the current button widget.

**Comment by derekdreery** [comment]
So you can set some things using the `Env` (there is an `EnvScope` widget I think if you only want to change it for some of your app), but yeah there could be mroe.

**Comment by totsteps** [comment]
There's a draft PR for this [#1493](https://github.com/linebender/druid/pull/1493).

**Comment by arthmis** [comment]
Yes I've noticed that. Hopefully that means it won't be necessary to reimplement button.
