### ISSUE TITLE
ListSelect::on_select provides previous selection to callback

### ISSUE THREAD

**Issue by tones111** [linebender/druid-widget-nursery#57]
When running the select example the application is supposed to print the selected city to the console, but it's printing the previously selected city instead.  For example, after initially launching, if the user mouse clicks the "to Sydney" list item ("to Tokyo" is selected initially) the application prints "Selected Destination: Tokyo".

This appears to be because the selected state is set true on [MouseDown](https://github.com/linebender/druid-widget-nursery/blob/1d3f4f2ef5cb296e05834d3a00425a0c9d918199/src/list_select.rs#L131), but the ListItem isn't updated until [MouseUp](https://github.com/linebender/druid-widget-nursery/blob/1d3f4f2ef5cb296e05834d3a00425a0c9d918199/src/list_select.rs#L191).

It seems like the list's on_select shouldn't fire until MouseUp has been received, but it also needs to propagate events through the list items first.  The list may also need to make sure it received both the MouseDown and MouseUp events because you wouldn't want the selection to fire if the mouse was dragged over the list then released.

**Comment by derekdreery** [comment]
Random comment: if you put `Closes #<issue number>` in a PR it will automatically close an issue when merged. Sorry if you already know this.
