### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by lisael** [linebender/druid-widget-nursery#60]
I guess it should be Apache-2.0 to match with druid.

**Comment by lisael** [comment]
There's another point, we don't keep the author list per file. (granted, git does.). Maybe we should require that contributors add their name in each file if they didn't contribute to druid itself. When a widget is included in druid we only have to copy/paste this list to `AUTHORS.md` to comply with Apache2.0 and keep track of copyright holders.

**Comment by derekdreery** [comment]
I think it's important to include authors, but I also want to keep contribution friction to a minimum. Do you think it is sufficient to use the git users (which does include real name if the user filled in `user.name` properly)?

@cmyr what are your thoughts on license? I've always used "Apache-2.0/MIT" but we could use "Apache-2.0" if you prefer.

**Comment by derekdreery** [comment]
Gonna add Apache-2.0/MIT.
