### ISSUE TITLE
[Meta] Add a 'Widget request' label in the issue tracker

### ISSUE THREAD

**Issue by lisael** [linebender/druid-widget-nursery#66]
Pros:
- A link in the 'README.md' to labeled issues would always be up-to-date
- Opening an issue is easier than creating a merge request (as currently suggested in the readme)
- People tend to open issues on the druid issue tracker for such requests. We can gently tell them to open an issue here and close the issue. It's better than keeping the issue open forever without any feedback or closing abruptly.
- Keep track of the advancement of design and implementation
  - less frustrating for the requester than a static list that never moves
  - a potential user / requester may give early feedback
  - avoid potential duplication of effort and encourage collaboration
- keep track of refused requests (too specific, too vague...)
  - "too specific" is quite subjective. If more users react to the closed issue, we may reconsider
- good entry point for new contributors

Cons:
- A bit of grooming is required, mostly to add the label and to clarify the demand, but I doubt there would be more than a couple of request per month (except maybe when druid hits HN front page)

Let me start: #65

**Comment by derekdreery** [comment]
Added
