### ISSUE TITLE
Add a Flex wrap widget

### ISSUE THREAD

**Issue by nicopap** [linebender/druid-widget-nursery#81]
I'm developing a naive wrapping flex widget similar to the one in the [web standard](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap). I don't think it's too ambitious, yet it would be very useful (I have a "list of tags" element) I feel it's something missing in the default widget library.

I will probably mirror the API for the default flex widget adding the extra necessary axis.

Would this be welcome in this repository?

**Comment by Maan2003** [comment]
it is certainly welcome. `Wrap` widget sounds similar, have you seen that?

**Comment by nicopap** [comment]
Awesome, what a fool I can be! I checked the repo but definitively overlooked the `Wrap` struct. This is very helpful,  thanks. I'll experiment with it and might contribute some improvements back if needed.

**Comment by nicopap** [comment]
For my use case, I stitched together the `List` widget from druid proper and the `Wrap` widget (into a `ListWrap` widget.)

I don't think a `Wrap` widget by itself makes sense, because whatever you put in it will most likely be a sort of dynamic list, and it doesn't play well with the current implementation.

But I also don't think a `ListWrap` widget which is basically a copy/pasted `List` with a custom layout makes sense. I will open an issue in the druid repo to discuss the potential for a `List` widget with pluggable `layout`. `List` should not have its own hard-coded layout, and this gives the opportunity to re-use `Flex` or any other layout widget code.
